hector_slam + gmapping
robotont/robotont_demos pull request #14
Opened 2020-11-17 07:22 UTC by mmaao

2020-11-17 16:34 UTC, kruusamae approved these changes

2020-11-23 23:16 UTC, Veix123 requested changes
please add dependencies to the package.xml, we should be able to install all the required deps with `rosdep install robotont_demos --ignore-src`

2020-11-23 23:16 UTC, Veix123 commented on launch/cartographer.launch
> +        <remap from="odom" to="$(arg robotont_ns)/odom"/>
I guess this falls into the big namespacing discussion, but can't we avoid the robotont_ns argument here by putting the whole node under ns=robotont namespace? In general, namespacing in ROS is designed not to be managed through custom variables in topic names.

2021-01-12 08:11 UTC, Veix123 approved these changes

2021-01-12 08:57 UTC, merged