Namespaced
robotont/robotont_demos pull request #15
Opened 2021-01-12 14:34 UTC by mmaao

2021-01-12 15:00 UTC, Veix123 requested changes

2021-01-12 15:00 UTC, Veix123 commented on config/robotont_2d_mapping.rviz
> +        veiku_base_footprint:
auch, minu commitist sisse jäänud prefixid... äkki saab ilma nendeta... ma näen, et rviz conf võiks olla selline, kus kõik autogenereeritud kraam on ära koristatud ja jäävad ainult need mida soovime määrata. kui muidugi rviz sellega nõus on :-)

2021-01-12 15:00 UTC, Veix123 commented on config/robotont_3d_mapping.rviz
> -      Depth Map Transport Hint: compressedDepth
Kas compressed tüüpi transport hint on default, et see siin eemaldatud on? Päris roboti puhul pole eriti mõeldav, et kompressimata kraam üle wifi lendab.

2021-01-12 15:00 UTC, Veix123 commented on launch/2d_slam.launch
>      <param name="odom/child_frame" value="base_footprint"/>
kas/miks sellele reale pole prefixit vaja? kas see võib olla warningute põhjus, mis namespacemisel 2dslamis lendasid?

2021-01-12 15:00 UTC, Veix123 commented on launch/gmapping.launch
> +        <param name="minimumScore" value="100" />7
mingi üleliigne "7" on siia rea lõppu ära eksinud

2021-01-18 14:55 UTC, mmaao commented on config/robotont_3d_mapping.rviz
> -      Depth Map Transport Hint: compressedDepth
Ei tohiks olla, ilmselt ma proovin midagi gazebo ajal ja kaotasin kogemata ära

2021-01-18 15:15 UTC, mmaao commented on launch/2d_slam.launch
>      <param name="odom/child_frame" value="base_footprint"/>
Proovisin koos nende ridadega ja ilma, warning oli mõlemat pidi, aga kaotasin nad nüüd ära, sest kasu neist ei olnud.

2021-01-25 14:59 UTC, kruusamae requested changes

2021-01-25 14:59 UTC, kruusamae commented on launch/2d_slam.launch
> +        <remap from="scan" to="scan"/>
kas see on päriselt vajalik? mida annab remap from scan to scan?

2021-01-25 14:59 UTC, kruusamae commented on launch/3d_mapping.launch
> +
kas siin ei õnnestuks dubleerimist vähendada, kui kasutaks hoopis eval_underscore_bypass lähenemist?

2021-01-25 14:59 UTC, kruusamae commented on launch/3d_mapping.launch
> +</launch>
lisa newline

2021-01-25 14:59 UTC, kruusamae commented on launch/ar_follow_the_leader.launch
> +        <param unless="$(eval prefix == '_')" name="output_frame"          type="string" value="$(arg prefix)camera_link" />
eval_underscore bypass?

2021-01-26 13:49 UTC, kruusamae commented on launch/3d_mapping.launch
> +      <remap unless="$(eval eval_underscore_bypass == '')" from="rgb/camera_info" to="/$(arg __ns)/camera/color/camera_info"/>
ma olen ikka pisut segaduses. kui ma küsisin, kas siin võiks kaaluda eval_underscore_bypassi, siis ma mõtlesin, et kas siin ei saaks luua mingit puhtamat lahendust, kus pole vaja neid if/unless tag'e kasutada?

2021-01-26 13:50 UTC, mmaao commented on launch/3d_mapping.launch
> +      <remap unless="$(eval eval_underscore_bypass == '')" from="rgb/camera_info" to="/$(arg __ns)/camera/color/camera_info"/>
Ilma kaikata läheb rtabmapi namespace ette ja tta ei remapi õiget topicut

2021-01-26 13:57 UTC, kruusamae commented on launch/3d_mapping.launch
> +      <remap unless="$(eval eval_underscore_bypass == '')" from="rgb/camera_info" to="/$(arg __ns)/camera/color/camera_info"/>
lõhnab nagu häkk. @Veix123 sinu mõtted? kas siin tuleks teha analoogselt rtabmap_ns_bypass? kus vaadatakse __ns väärtust, kui see on tühis, siis prefix = "/" ja kui ei ole tühi, siis prefix = "/$(arg __ns)". ja siis remappimisel panna ikkagi kõigile prefix ette?

2021-01-26 13:57 UTC, kruusamae commented on launch/3d_mapping.launch
> +      <remap unless="$(eval eval_underscore_bypass == '')" from="rgb/camera_info" to="/$(arg __ns)/camera/color/camera_info"/>
ja muidugi kommentaarid juurde, sest häkk

2021-01-27 15:41 UTC, kruusamae requested changes

2021-01-27 15:41 UTC, kruusamae commented on launch/cartographer.launch
>      </node>
<node> taanded üle vaadata

2021-01-29 10:33 UTC, Veix123 approved these changes

2021-01-29 10:33 UTC, Veix123 commented on launch/2d_slam.launch
>      <param name="odom/child_frame" value="base_footprint"/>
oki, praegu paistab, et näiteks fixed_frame määratakse vähemalt robotont_navigation kimbus läbi yaml faili, seega siin olekski üleliigne.

2021-01-29 10:33 UTC, Veix123 commented on launch/cartographer.launch
> -        <remap from="echoes" to="scan" />
@mmaao Kas selle remap-i eemaldamine midagi katki ei tee? Ei leia esimese hooga kohta kus kartograaferile öeldakse et loe scan-i...

ok ise küsin ise vastan: lk 12 https://buildmedia.readthedocs.org/media/pdf/google-cartographer-ros/latest/google-cartographer-ros.pdf:
If you use only one sensor_msgs/LaserScan topic, it is expected to be named scan. If you have more,
they should be named scan_1, scan_2 etc. . .

2021-01-29 11:24 UTC, kruusamae approved these changes

2021-01-29 11:25 UTC, merged